version: "3.7"
services:

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_MULTIPLE_DATABASES: ${DB_DATABASES}
    volumes:
      - ./config/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./.tmp/db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning

  api:
    image: ${DOCKER_BOT}
    command:
      - npm
      - run-script
      - api
    environment:
      LOGGING_LEVEL: info
      API_SECURITY_TOKEN: ${API_SECURITY_TOKEN}
      DATABASE_URL: ${DATABASE}
      API_PORT:  ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    restart: always


  chain:
    image: ${DOCKER_BOT}
    command:
      - npm
      - run-script
      - chain
    environment:
      LOGGING_LEVEL: info
      DATABASE_URL: ${DATABASE}
      GRAPH_URL: ${GRAPH_URL}
      CHAIN_RPC_URL: ${CHAIN_RPC_URL}
      CHAIN_ACCOUNT: ${CHAIN_ACCOUNT}
    depends_on:
      - db
      - api
    restart: always


  aggregation:
    image: ${DOCKER_BOT}
    command:
      - npm
      - run-script
      - service
    environment:
      LOGGING_LEVEL: info
      DATABASE_URL: ${DATABASE}
    depends_on:
      - db
      - api
    restart: always


  # discord:
  #   image: ${DOCKER_BOT}
  #   command:
  #     - npm
  #     - run-script
  #     - discord
  #   environment:
  #     LOGGING_LEVEL: info
  #     DATABASE_URL: ${DATABASE}
  #     DISCORD_BOT_KEY:
  #   depends_on:
  #     - db
  #     - api
  #  restart: always


  # twitter:
  #   image: ${DOCKER_BOT}
  #   command:
  #     - npm
  #     - run-script
  #     - twitter
  #   environment:
  #     LOGGING_LEVEL: info
  #     DATABASE_URL: ${DATABASE}
  #     TWITTER_BEARER_TOKEN:
  #   depends_on:
  #     - db
  #     - api
  #  restart: always


  # epic-games:
  #   image: ${DOCKER_BOT}
  #   command:
  #     - npm
  #     - run-script
  #     - epicGames
  #   environment:
  #     LOGGING_LEVEL: info
  #     DATABASE_URL: ${DATABASE}
  #     EPIC_GAMES_DEPLOYMENT_ID:
  #     EPIC_GAMES_CLIENT_ID:
  #     EPIC_GAMES_CLIENT_SECRET:
  #   depends_on:
  #     - db
  #     - api
  #  restart: always

